---
- name: Create user for Alessandro
  user:
    append: yes
    groups: ['docker', 'root']
    name: Ale
    shell: /bin/bash

- name: Set authorized key for Alessandro from file
  authorized_key:
    user: Ale
    state: present
    key: "{{ lookup('file', 'files/public_keys/Ale') }}"
