global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'central-monitoring-system'
  
rule_files:
  - "general.yml"

scrape_configs:
  - job_name: 'mysqlexporter01'
    scrape_interval: 1s
    static_configs:
      - targets: ['mysqlexporter:9104']
