all:
  children:
    application:
      hosts:
        application1:
          short_name: app1
          disk_name: uhopper-disk-1
          ansible_ssh_host: 35.198.139.126

  vars:
    ansible_connection: ssh
    ansible_user: ansible
