all:
  children:
    servers:
      hosts:
        server1:
          short_name: server1
          # disk_name: disk-1
          ansible_ssh_host: 35.202.215.67
          manage_lvm: true
          lvm_groups:
            - vgname: vg1
              disks:
                - /dev/disk/by-id/google-disk-1
              create: true
              lvnames:
                - lvname: docker
                  size: 5g
                  create: true
                  filesystem: ext4
                  mount: true
                  mntp: /mnt/docker

  vars:
    ansible_connection: ssh
    ansible_user: ansible
