all:
  children:
    application:
      hosts:
        application1:
          short_name: app1
          # disk_name: disk-1
          ansible_ssh_host: 35.198.139.126
          manage_lvm: true
          lvm_groups:
            - vgname: appvg1
              disks:
                - /dev/disk/by-id/google-disk-2
              create: true
              lvnames:
                - lvname: application_mysql
                  size: 5g
                  create: true
                  filesystem: ext4
                  mount: true
                  mntp: /mnt/application_mysql

  vars:
    ansible_connection: ssh
    ansible_user: ansible
