- hosts: all
  become: true
  roles:
    - {role: pip, tags: role_pip}
    - {role: os, tags: role_os}
    - {role: lvm, tags: role_lvm}
    - {role: docker, tags: role_docker}
    - {role: identities, tags: role_identities}

- hosts: server1
  become: true
  roles:
    # - disk
    - {role: application, tags: role_application}
